# Generated by Django 3.1 on 2022-11-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_remove_cartitem_variations'),
        ('store', '0005_auto_20221119_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
