# Generated by Django 3.1 on 2022-11-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20221120_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Bid_owner',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='current_winner',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(default='shoes', null=True),
        ),
    ]
